server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emp_mg
    username: postgres
    password: 8383


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update